FIND_PATH(LIBSTLPORT_INCLUDE_DIR
	NAMES stl/_stlport_version.h
	PATHS
	/usr/include/stlport
	)

FIND_LIBRARY(LIBSTLPORT_LIBRARY NAMES stlport libstlport)

IF(LIBSTLPORT_INCLUDE_DIR AND LIBSTLPORT_LIBRARY)
	SET(LIBSTLPORT_FOUND TRUE CACHE BOOLEAN "Was libstlport found?")
ELSE(LIBSTLPORT_INCLUDE_DIR AND LIBSTLPORT_LIBRARY)
	SET(LIBSTLPORT_FOUND FALSE CACHE BOOLEAN "Was libstlport found?")
ENDIF(LIBSTLPORT_INCLUDE_DIR AND LIBSTLPORT_LIBRARY)

SET(LIBSTLPORT_LIBRARIES ${LIBSTLPORT_LIBRARY})
