FIND_PATH(LIBZ_H NAMES zlib.h)
FIND_LIBRARY(LIBZ_LIB NAMES z zlib libz)

IF(LIBZ_H AND LIBZ_LIB)
	SET(ZLIB_FOUND TRUE CACHE BOOL Was ZLIB found)
ELSE(LIBZ_H AND LIBZ_LIB)
	SET(ZLIB_FOUND FALSE CACHE BOOL Was ZLIB found)
ENDIF(LIBZ_H AND LIBZ_LIB)
