FIND_PATH(LIBSTLPORT_HEADERS
	NAMES stl/_stlport_version.h
	PATHS
	/usr/include/stlport
	)
MESSAGE("Found STLPort headers in ${LIBSTLPORT_HEADERS}")

FIND_LIBRARY(LIBSTLPORT_LIB NAMES stlport libstlport)
MESSAGE("Found STLPort library in ${LIBSTLPORT_LIB}")

IF(LIBSTLPORT_HEADERS AND LIBSTLPORT_LIB)
	SET(LIBSTLPORT_FOUND TRUE CACHE BOOLEAN "Was libstlport found?")
ELSE(LIBSTLPORT_HEADERS AND LIBSTLPORT_LIB)
	SET(LIBSTLPORT_FOUND FALSE CACHE BOOLEAN "Was libstlport found?")
ENDIF(LIBSTLPORT_HEADERS AND LIBSTLPORT_LIB)
