#ifndef PODOFO_PDFVERSION_H
#define PODOFO_PDFVERSION_H

#define PODOFO_MAJOR PODOFO_VERSION_MAJOR
#define PODOFO_MINOR PODOFO_VERSION_MINOR
#define PODOFO_REVISION PODOFO_VERSION_PATCH

#define PODOFO_VERSION_STRING PODOFO_VERSION_STR

#endif
