name: build-mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ctestArgs:
        description: 'CTest arguments'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Cleanup workspace and dependencies
      run: |
        rm -rf ${{github.workspace}}/build
        rm -rf ${{github.workspace}}/html
        brew list | xargs brew uninstall
        brew autoremove
        brew cleanup -s

    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Install deps
      # NOTE: We need to ensure jpeg-turbo is at least version 2.14
      run: brew update
           && brew install fontconfig freetype openssl libxml2 jpeg-turbo libpng libtiff libidn doxygen cmake

    - name: Configure CMake
      # NOTE: OpenSSL prefix must be explicitly set
      run:
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_FIND_FRAMEWORK=NEVER -DCMAKE_PREFIX_PATH=`brew --prefix` -DFontconfig_INCLUDE_DIR=`brew --prefix fontconfig`/include -DOPENSSL_ROOT_DIR=`brew --prefix openssl@3` 

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest ${{ github.event.inputs.ctestArgs }}

    - name: Generate Doxygen Documentation
      run: |
        doxygen ${{github.workspace}}/build/Doxyfile
      id: doxygen
      continue-on-error: true

    - name: Upload Doxygen Documentation
      if: steps.doxygen.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ${{github.workspace}}/build/documentation
