name: build-documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: |
          doxygen ${{ github.workspace }}/Doxyfile
        id: doxygen

      - name: Upload Doxygen Documentation
        if: steps.doxygen.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ${{ github.workspace }}/documentation
